# Generated by Django 6.0.5 on 2026-05-11 11:22

import django.db.models.deletion
import frais.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('transport', 'Transport'), ('hebergement', 'Hébergement'), ('restauration', 'Restauration'), ('autre', 'Autres dépenses')], max_length=20, verbose_name='Type de frais')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (MAD)')),
                ('date_frais', models.DateField(verbose_name='Date du frais')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_manager', models.TextField(blank=True, verbose_name='Commentaire manager')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='missions.mission', verbose_name='Mission')),
                ('validé_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frais_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=frais.models.justificatif_path, verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='frais.frais')),
            ],
            options={
                'verbose_name': 'Justificatif',
            },
        ),
    ]
