# Generated by Django 6.0.5 on 2026-05-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frais',
            old_name='validé_par',
            new_name='valide_par',
        ),
    ]
